"""added appointment functionality

Revision ID: 211c114290d1
Revises: 1f5047248db0
Create Date: 2024-09-22 08:23:50.840419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '211c114290d1'
down_revision = '1f5047248db0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purpose', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('purpose')

    # ### end Alembic commands ###
